### ISSUE TITLE
Multiple annotations on a pixel

### ISSUE THREAD

**Issue by vatempeli** [ome/ngff#121]
Hello everyone! Do you possibly know if I can do multiple annotations on a pixel via QuPath? I am currently using machine learning procedure for my classifications. But what can I do if a specific area is two things (e.g. a cell on a vessel) and I want the area etc. measurements of both of them? 
![Στιγμιότυπο οθόνης 2022-05-21 170202](https://user-images.githubusercontent.com/105979314/169657401-486e4bdf-ee4d-4667-b6dd-d8561ca4a4a3.png)

**Comment by sbesson** [comment]
@vatempeli your question is related to QuPath usage rather than the OME-NGFF specification. Closing this issue as this is a separate application and GitHub organisation so we cannot easily transfer. I invite you to either reopen it against https://github.com/qupath/qupath/ or create a new post under https://forum.image.sc.
